/**
 * API Capture Script
 * 
 * This script captures API responses from the staging instance
 * and generates test data fixtures.
 * 
 * Usage: npm run test:e2e:capture-api
 */

import axios from 'axios';
import * as fs from 'fs';
import * as path from 'path';

const API_BASE_URL = process.env.API_BASE_URL || 'http://localhost:8080/api';

function extractSteamId(fullId: string): string {
  if (!fullId) return '';
  const match = fullId.match(/\[U:\d+:(\d+)\]/);
  return match ? match[1] : fullId;
}

interface ApiResponse {
  endpoint: string;
  data: any;
}

async function captureApiResponse(endpoint: string): Promise<any> {
  try {
    const url = `${API_BASE_URL}${endpoint}`;
    console.log(`Capturing: ${url}`);
    const response = await axios.get(url);
    return response.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      console.error(`Error capturing ${endpoint}:`, error.message);
      if (error.response) {
        console.error(`Status: ${error.response.status}`);
      }
    }
    return null;
  }
}

async function main() {
  console.log('Starting API capture from staging instance...');
  console.log(`API Base URL: ${API_BASE_URL}\n`);

  const responses: ApiResponse[] = [];

  // Capture games
  console.log('1. Capturing games...');
  const games = await captureApiResponse('/games');
  if (games && Array.isArray(games) && games.length > 0) {
    responses.push({ endpoint: '/games', data: games });
    console.log(`   ✓ Captured ${games.length} games`);
  } else {
    console.log('   ✗ No games found');
  }

  // Capture rankings
  console.log('\n2. Capturing rankings...');
  const rankings = await captureApiResponse('/rankings');
  if (rankings && Array.isArray(rankings) && rankings.length > 0) {
    responses.push({ endpoint: '/rankings', data: rankings });
    console.log(`   ✓ Captured ${rankings.length} players`);
  } else {
    console.log('   ✗ No rankings found');
  }

  // Capture game details for first game
  if (games && Array.isArray(games) && games.length > 0) {
    const firstGameId = games[0].id;
    console.log(`\n3. Capturing game details for game ${firstGameId}...`);
    const gameDetails = await captureApiResponse(`/games/${firstGameId}/details`);
    if (gameDetails) {
      responses.push({ endpoint: `/games/${firstGameId}/details`, data: gameDetails });
      console.log('   ✓ Captured game details');

      // Capture round details for first round
      if (gameDetails.rounds && gameDetails.rounds.length > 0) {
        const firstRoundNumber = 1;
        console.log(`\n4. Capturing round details for round ${firstRoundNumber}...`);
        const roundDetails = await captureApiResponse(`/games/${firstGameId}/rounds/${firstRoundNumber}`);
        if (roundDetails) {
          responses.push({ endpoint: `/games/${firstGameId}/rounds/${firstRoundNumber}`, data: roundDetails });
          console.log('   ✓ Captured round details');
        }
      }
    }
  }

  // Capture player profile for first player
  if (rankings && Array.isArray(rankings) && rankings.length > 0) {
    const firstPlayerId = extractSteamId(rankings[0].playerId);
    console.log(`\n5. Capturing player profile for player ${firstPlayerId}...`);
    const playerProfile = await captureApiResponse(`/players/${encodeURIComponent(firstPlayerId)}`);
    if (playerProfile) {
      responses.push({ endpoint: `/players/${firstPlayerId}`, data: playerProfile });
      console.log('   ✓ Captured player profile');
    }
  }

  // Save responses to JSON file
  const outputPath = path.join(__dirname, '../fixtures/api-responses.json');
  fs.writeFileSync(outputPath, JSON.stringify(responses, null, 2));
  console.log(`\n✓ Saved API responses to: ${outputPath}`);

  // Generate TypeScript fixture file
  generateTestDataFixture(responses);
}

function generateTestDataFixture(responses: ApiResponse[]) {
  const gamesResponse = responses.find(r => r.endpoint === '/games');
  const rankingsResponse = responses.find(r => r.endpoint === '/rankings');
  const gameDetailsResponse = responses.find(r => r.endpoint.includes('/details'));
  const roundDetailsResponse = responses.find(r => r.endpoint.includes('/rounds/'));
  const playerProfileResponse = responses.find(r => r.endpoint.includes('/players/'));

  let fixtureContent = `/**
 * Test Data Fixtures - Auto-generated from API capture
 * Generated: ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate by running: npm run test:e2e:capture-api
 */

import type { TestGame, TestPlayer, TestGameDetails, TestRoundDetails, TestPlayerProfile } from './test-data';

export const capturedTestData = {
`;

  // Games
  if (gamesResponse && Array.isArray(gamesResponse.data)) {
    fixtureContent += `  games: ${JSON.stringify(gamesResponse.data.slice(0, 2), null, 4)} as TestGame[],\n\n`;
  } else {
    fixtureContent += `  games: [] as TestGame[],\n\n`;
  }

  // Players
  if (rankingsResponse && Array.isArray(rankingsResponse.data)) {
    fixtureContent += `  players: ${JSON.stringify(rankingsResponse.data.slice(0, 10), null, 4)} as TestPlayer[],\n\n`;
  } else {
    fixtureContent += `  players: [] as TestPlayer[],\n\n`;
  }

  // Game Details
  if (gameDetailsResponse) {
    fixtureContent += `  gameDetails: ${JSON.stringify(gameDetailsResponse.data, null, 4)} as TestGameDetails,\n\n`;
  } else {
    fixtureContent += `  gameDetails: null as TestGameDetails | null,\n\n`;
  }

  // Round Details
  if (roundDetailsResponse) {
    fixtureContent += `  roundDetails: ${JSON.stringify(roundDetailsResponse.data, null, 4)} as TestRoundDetails,\n\n`;
  } else {
    fixtureContent += `  roundDetails: null as TestRoundDetails | null,\n\n`;
  }

  // Player Profile
  if (playerProfileResponse) {
    fixtureContent += `  playerProfile: ${JSON.stringify(playerProfileResponse.data, null, 4)} as TestPlayerProfile,\n`;
  } else {
    fixtureContent += `  playerProfile: null as TestPlayerProfile | null,\n`;
  }

  fixtureContent += `};\n`;

  const outputPath = path.join(__dirname, '../fixtures/captured-test-data.ts');
  fs.writeFileSync(outputPath, fixtureContent);
  console.log(`✓ Generated test data fixture: ${outputPath}`);
}

// Run if executed directly
if (require.main === module) {
  main().catch(console.error);
}

export { main as captureApiResponses };
