runtime: java17

# GAE service configuration
service: default

# Environment variables
env_variables:
  SPRING_PROFILES_ACTIVE: "gae"
  
# Instance class (F1 is the cheapest)
instance_class: F2

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 3
  healthy_threshold: 2

# Liveness check configuration  
liveness_check:
  path: "/api/rankings/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Readiness check configuration
readiness_check:
  path: "/api/rankings/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 300